/*
CREATE TABLE IF NOT EXISTS users(
    user_id INT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    user_name VARCHAR(50) NOT NULL,
    rantxt VARCHAR(50) NOT NULL DEFAULT 10,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pardoned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
); ALTER TABLE
    users AUTO_INCREMENT = 2001;

*/